# Numpy Exercise

***
### Overview on Numpy

Please install numpy library via Pip Manager / command prompt

Convert a list of numeric value into a one-dimensional NumPy array
<br>Expected Output:
<br>Original List: [12.23, 13.32, 100, 36.32]
<br>One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [26]:
import numpy as np
l = [12.23, 13.32, 100, 36.32]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ", a)

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]


Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. 
Expected Output:
<br>[[ 2 3 4]
<br>[ 5 6 7]
<br>[ 8 9 10]]


In [27]:
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Write a NumPy program to reverse an array (first element becomes last). 
<br>Original array:
<br>[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
<br>Reverse array:
<br>[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [28]:
x = np.arange(12, 38)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 
<br>Expected Output:
<br>Original array:
<br>[[ 1. 1. 1. 1. 1.]
<br>...................
<br>[ 1. 1. 1. 1. 1.]]
<br>1 on the border and 0 inside in the array
<br>[[ 1. 1. 1. 1. 1.]
<br>...................
<br>[ 1. 1. 1. 1. 1.]]

In [29]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Write a NumPy program to convert a list and tuple into arrays. 
<br>List to array:
<br>[1 2 3 4 5 6 7 8]
<br>Tuple to array:
<br>[[8 4 6]
<br>[1 2 3]]

In [30]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array. 
<br>Sample Array [0, 12, 45.21 ,34, 99.91]
<br>Expected Output:
<br>Values in Fahrenheit degrees:
<br>[ 0. 12. 45.21 34. 99.91]
<br>Values in Centigrade degrees:
<br>[-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [31]:
import numpy as np
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:") 
print(5*F/9 - 5*32/9)

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Write a NumPy program to test whether each element of a 1-D array is also present in a second array. 
<br>Expected Output:
<br>Array1: [ 0 10 20 40 60]
<br>Array2: [0, 40]
<br>Compare each element of array1 and array2
<br>[ True False False True False]

In [32]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [0, 40]
print("Array2: ",array2)
print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [0, 40]
Compare each element of array1 and array2
[ True False False  True False]


Write a NumPy program to get the unique elements of an array. 
<br>Expected Output:
<br>Original array:
<br>[10 10 20 20 30 30]
<br>Unique elements of the above array:
<br>[10 20 30]
<br>Original array:
<br>[[1 1]
<br>[2 3]]
<br>Unique elements of the above array:
<br>[1 2 3]

In [33]:
x = np.array([10, 10, 20, 20, 30, 30])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))
x = np.array([[1, 1], [2, 3]])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays. 
<br>Array1: [ 0 10 20 40 60 80]
<br>Array2: [10, 30, 40, 50, 70]
<br>Unique values that are in only one (not both) of the input arrays:
<br>[ 0 20 30 50 60 70 80]

In [34]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays. 
<br>Array1: [ 0 10 20 40 60 80]
<br>Array2: [10, 30, 40, 50, 70]
<br>Unique sorted array of values that are in either of the two input arrays:
<br>[ 0 10 20 30 40 50 60 70 80]

In [35]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique sorted array of values that are in either of the two input arrays:")
print(np.union1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique sorted array of values that are in either of the two input arrays:
[ 0 10 20 30 40 50 60 70 80]


Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array. 
<br>Original array: [1 2 3 4 5 6]
<br>Maximum Values: 5
<br>Minimum Values: 0

In [36]:
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array: ",x)
print("Maximum Values: ",np.argmax(x))
print("Minimum Values: ",np.argmin(x))

Original array:  [1 2 3 4 5 6]
Maximum Values:  5
Minimum Values:  0


Write a NumPy program to change the dimension of an array. 
<br>Expected Output:
<br>6 rows and 0 columns
<br>(6,)
<br>(3, 3) -> 3 rows and 3 columns
<br>[[1 2 3]
<br>[4 5 6]
<br>[7 8 9]]
<br>Change array shape to (3, 3) -> 3 rows and 3 columns
<br>[[1 2 3]
<br>[4 5 6]
<br>[7 8 9]]

In [37]:
x = np.array([1, 2, 3, 4, 5, 6])
print("6 rows and 0 columns")
print(x.shape)

y = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("(3, 3) -> 3 rows and 3 columns ")
print(y)

x = np.array([1,2,3,4,5,6,7,8,9])
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
x.shape = (3, 3)
print(x)

6 rows and 0 columns
(6,)
(3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Write a NumPy program to create a new shape to an array without changing its data. 
<br>Reshape 3x2:
<br>[[1 2]
<br>[3 4]
<br>[5 6]]
<br>Reshape 2x3:
<br>[[1 2 3]
<br>[4 5 6]]

In [38]:
x = np.array([1, 2, 3, 4, 5, 6])
y = np.reshape(x,(3,2))
print("Reshape 3x2:")
print(y)
z = np.reshape(x,(2,3))
print("Reshape 2x3:")
print(z)

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


Write a NumPy program to change the data type of an array. 
<br>Expected Output:
<br>[[ 2 4 6]
<br>[ 6 8 10]]
<br>Data type of the array x is: int32
<br>New Type: float64
<br>[[ 2. 4. 6.]
<br>[ 6. 8. 10.]]

In [39]:
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
print("Data type of the array x is:",x.dtype)
# Change the data type of x
y = x.astype(float)
print("New Type: ",y.dtype)
print(y)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
New Type:  float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


Write a NumPy program to collapse a 3-D array into one dimension array. 
<br>Expected Output:
<br>3-D array:
<br>[[ 1. 0. 0.]
<br>[ 0. 1. 0.]
<br>[ 0. 0. 1.]]
<br>One dimension array:
<br>[ 1. 0. 0. 0. 1. 0. 0. 0. 1.]

In [40]:
x = np.eye(3)
print("3-D array:")
print(x)
f = np.ravel(x, order='F')
print("One dimension array:")
print(f)

3-D array:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
One dimension array:
[1. 0. 0. 0. 1. 0. 0. 0. 1.]


Write a NumPy program to interchange two axes of an array. 
<br>Sample array: [[1 2 3]]
<br>Expected Output:
<br>[[1]
<br>[2]
<br>[3]]

In [41]:
x = np.array([[1,2,3]])
print(x)
y =  np.swapaxes(x,0,1)
print(y)

[[1 2 3]]
[[1]
 [2]
 [3]]


Write a NumPy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order. 
<br>Expected Output:
<br>Original array: [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14]
<br>After splitting:
<br>[array([1, 2]), array([3, 4, 5, 6]), array([ 7, 8, 9, 10, 11, 12, 13, 14])]

In [42]:
x = np.arange(1, 15)
print("Original array:",x)
print("After splitting:")
print(np.split(x, [2, 6]))

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After splitting:
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


Write a NumPy program to test whether specified values are present in an array. 
<br>Expected Output:
<br>Original array:
<br>[[ 1.12 2. 3.45]
<br>[ 2.33 5.12 6. ]]
<br>True
<br>False
<br>True
<br>False
<br>True

In [43]:
x = np.array([[1.12, 2.0, 3.45], [2.33, 5.12, 6.0]], float) 
print("Original array:")
print(x)
print(2 in x)
print(0 in x)
print(6 in x)
print(2.3 in x)
print(5.12 in x)

Original array:
[[1.12 2.   3.45]
 [2.33 5.12 6.  ]]
True
False
True
False
True


Write a NumPy program to access an array by column. 
<br>Expected Output:
<br>Original array elements:
<br>[[0 1]
<br>[2 3]
<br>[4 5]]
<br>Access an array by column:
<br>First column:
<br>[0 1]
<br>Second column:
<br>[2 3]
<br>Third column:
<br>[4 5]

In [44]:
x= np.arange(9).reshape(3,3)
print("Original array elements:")
print(x)
print("Access an array by column:")
print("First column:")
print(x[:,0])
print("Second column:")
print(x[:,1])
print("Third column:")
print(x[:,2])

Original array elements:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Access an array by column:
First column:
[0 3 6]
Second column:
[1 4 7]
Third column:
[2 5 8]


Write a NumPy program to replace all elements of NumPy array that are greater than specified array. 
<br>
<br>Expected Output:
<br>Original array:
<br>[[ 0.42436315 0.48558583 0.32924763]
<br>[ 0.7439979 0.58220701 0.38213418]
<br>[ 0.5097581 0.34528799 0.1563123 ]]
<br>Replace all elements of the said array with .5 which are greater than. 5
<br>[[ 0.42436315 0.48558583 0.32924763]
<br>[ 0.5 0.5 0.38213418]
<br>[ 0.5 0.34528799 0.1563123 ]]

In [45]:
x = np.array([[ 0.42436315, 0.48558583, 0.32924763], [ 0.7439979,0.58220701,0.38213418], [ 0.5097581,0.34528799,0.1563123 ]])
print("Original array:")
print(x)
print("Replace all elements of the said array with .5 which are greater than .5")
x[x > .5] = .5
print(x)

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


Write a NumPy program to remove the negative values in a NumPy array with 0. 
<br>
<br>Expected Output:
<br>Original array:
<br>[-1 -4 0 2 3 4 5 -6]
<br>Replace the negative values of the said array with 0:
<br>[0 0 0 2 3 4 5 0]

In [46]:
x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])
print("Original array:")
print(x)
print("Replace the negative values of the said array with 0:")
x[x < 0] = 0
print(x)

Original array:
[-1 -4  0  2  3  4  5 -6]
Replace the negative values of the said array with 0:
[0 0 0 2 3 4 5 0]


Write a NumPy program to select indices satisfying multiple conditions in a NumPy array. 
<br>Sample array :
<br>a = np.array([97, 101, 105, 111, 117])
<br>b = np.array(['a','e','i','o','u'])
<br>Note: Select the elements from the second array corresponding to elements in the first array that are greater than 100 and less than 110
<br>Expected Output:
<br>Original arrays
<br>[ 97 101 105 111 117]
<br>['a' 'e' 'i' 'o' 'u']
<br>Elements from the second array corresponding to elements in the first
<br>array that are greater than 100 and less than 110:
<br>['e' 'i']

In [47]:
a = np.array([97, 101, 105, 111, 117])
b = np.array(['a','e','i','o','u'])
print("Original arrays")
print(a)
print(b)
print("Elements from the second array  corresponding to elements in the first array  that are greater than 100 and less than 110:")
print(b[(100 < a) & (a < 110)])


Original arrays
[ 97 101 105 111 117]
['a' 'e' 'i' 'o' 'u']
Elements from the second array  corresponding to elements in the first array  that are greater than 100 and less than 110:
['e' 'i']


Write a NumPy program to divide each row by a vector element. 
<br>Expected Output:
<br>Original array:
<br>[[20 20 20]
<br>[30 30 30]
<br>[40 40 40]]
<br>Vector:
<br>[20 30 40]
<br>[[ 1. 1. 1.]
<br>[ 1. 1. 1.]
<br>[ 1. 1. 1.]]

In [48]:
x = np.array([[20,20,20],[30,30,30],[40,40,40]])
print("Original array:")
print(x)
v = np.array([20,30,40])
print("Vector:")
print(v)
print(x / v[:,None])

Original array:
[[20 20 20]
 [30 30 30]
 [40 40 40]]
Vector:
[20 30 40]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Write a NumPy program to sum and compute the product of a NumPy array elements. 
<br>Expected Output:
<br>Original array:
<br>[ 10. 20. 30.]
<br>Sum of the array elements:
<br>60.0
<br>Product of the array elements:
<br>6000.0

In [49]:
x = np.array([10, 20, 30], float)
print("Original array:")
print(x)
print("Sum of the array elements:")
print(x.sum())
print("Product of the array elements:")
print(x.prod())

Original array:
[10. 20. 30.]
Sum of the array elements:
60.0
Product of the array elements:
6000.0


Write a NumPy program to read a CSV data file and store records in an array. 
<br>Sample CSV file: fdata.csv
<br>Date,Open,High,Low,Close
<br>03-10-16,774.25,776.065002,769.5,772.559998
<br>.................
<br>07-10-16,779.659973,779.659973,770.75,775.080017
<br>Sample Output:
<br>[(b'Date', nan, nan, nan, nan)
<br>(b'03-10-16', 774.25, 776.065, 769.5 , 772.56)
<br>......................
<br>(b'07-10-16', 779.66, 779.66 , 770.75, 775.08)]

In [50]:
from numpy import genfromtxt
csv_data = genfromtxt('fdata.csv', dtype=['S10','float32','float32','float32','float32'], delimiter=",")
print(csv_data)

[(b'Date',    nan,     nan,    nan,    nan)
 (b'10-03-16', 774.25, 776.065, 769.5 , 772.56)
 (b'10-04-16', 776.03, 778.71 , 772.89, 776.43)
 (b'10-05-16', 779.31, 782.07 , 775.65, 776.47)
 (b'10-06-16', 779.  , 780.48 , 775.54, 776.86)
 (b'10-07-16', 779.66, 779.66 , 770.75, 775.08)]


Write a NumPy program to extract first, third and fifth elements of the third and fifth rows from a given (6x6) array. 
<br>Sample Output:
<br>Original array:
<br>[[ 0 1 2 3 4 5]
<br>................
<br>[30 31 32 33 34 35]]
<br>Extracted data: First, third and fifth elements of the third and fifth rows
<br>[[12 14 16]
<br>[24 26 28]]

In [51]:
arra_data = np.arange(0,36).reshape((6, 6))
print("Original array:")
print(arra_data)
print("\nExtracted data: First, third and fifth elements of the third and fifth rows")
print(arra_data[2::2, ::2]) 

Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Extracted data: First, third and fifth elements of the third and fifth rows
[[12 14 16]
 [24 26 28]]


Write a NumPy program to add two arrays A and B of sizes (3,3) and (,3). 
<br>Sample Output:
<br>Original array:
<br>Array-1
<br>[[1. 1. 1.]
<br>[1. 1. 1.]
<br>[1. 1. 1.]]
<br>Array-2
<br>[0 1 2]
<br>A + B:
<br>[[1. 2. 3.]
<br>[1. 2. 3.]
<br>[1. 2. 3.]]

In [52]:
A = np.ones((3,3))
B = np.arange(3)
print("Original array:")
print("Array-1")
print(A)
print("Array-2")
print(B)
print("A + B:")
new_array = A + B
print(new_array)

Original array:
Array-1
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array-2
[0 1 2]
A + B:
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


Write a NumPy program to calculate the sum of all columns of a 2D NumPy array. 
<br>Sample Output:
<br>Original array:
<br>[[ 0 1 2 3 4 5 6 7 8]
<br>[ 9 10 11 12 13 14 15 16 17]
<br>[18 19 20 21 22 23 24 25 26]
<br>[27 28 29 30 31 32 33 34 35]]
<br>Sum of all columns:
<br>[54 58 62 66 70 74 78 82 86]

In [53]:
num = np.arange(36)
arr1 = np.reshape(num, [4, 9])
print("Original array:")
print(arr1)
result  = arr1.sum(axis=0)
print("\nSum of all columns:")
print(result)

Original array:
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]

Sum of all columns:
[54 58 62 66 70 74 78 82 86]


Write a NumPy program to combine last element with first element of two given ndarray with different shapes. 
<br>Original arrays:
<br>['PHP', 'JS', 'C++']
<br>['Python', 'C#', 'NumPy']
<br>After Combining:
<br>['PHP' 'JS' 'C++Python' 'C#' 'NumPy']

In [54]:
array1 = ['PHP','JS','C++']
array2 = ['Python','C#', 'NumPy']    
print("Original arrays:")          
print(array1)
print(array2)          
result  = np.r_[array1[:-1], [array1[-1]+array2[0]], array2[1:]]   
print("\nAfter Combining:")       
print(result)

Original arrays:
['PHP', 'JS', 'C++']
['Python', 'C#', 'NumPy']

After Combining:
['PHP' 'JS' 'C++Python' 'C#' 'NumPy']


Write a NumPy program to subtract the mean of each row of a given matrix. 
<br>Original matrix:
<br>[[0.59243452 0.51883289 0.03732848 0.49544926 0.22637201 0.45750412
<br>0.81614237 0.86681236 0.95482226 0.54789281]
<br>..............
<br>[0.14428353 0.20556412 0.97059136 0.53545871 0.93828877 0.81535277
<br>0.60563373 0.47543413 0.0468766 0.97460889]]
<br>Subtract the mean of each row of the said matrix:
<br>[[ 0.04107541 -0.03252622 -0.51403063 -0.05590985 -0.3249871 -0.09385499
<br>0.26478326 0.31545325 0.40346315 -0.0034663 ]
<br>....................
<br>[-0.42692573 -0.36564514 0.3993821 -0.03575056 0.36707951 0.24414351
<br>0.03442447 -0.09577513 -0.52433266 0.40339963]]

In [55]:
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.38416745 0.85845208 0.06763701 0.26700212 0.24002672 0.35914202
  0.87652043 0.9672092  0.99488117 0.51428918]
 [0.30326028 0.76773482 0.11157602 0.70834462 0.74876148 0.73510079
  0.9509995  0.27008801 0.6737293  0.42642885]
 [0.90053782 0.47560824 0.367416   0.42419383 0.72660661 0.43258356
  0.54909697 0.41294478 0.64902379 0.9411624 ]
 [0.38898604 0.74764598 0.1895657  0.73339292 0.41596697 0.39980778
  0.62999818 0.23726234 0.84056763 0.39430948]
 [0.72605277 0.03261777 0.67677364 0.60229811 0.92471754 0.98763856
  0.73161266 0.80268822 0.28842293 0.9017354 ]]

Subtract the mean of each row of the said matrix:

[[-0.16876529  0.30551934 -0.48529573 -0.28593062 -0.31290602 -0.19379072
   0.32358769  0.41427646  0.44194843 -0.03864356]
 [-0.26634209  0.19813246 -0.45802635  0.13874225  0.17915911  0.16549842
   0.38139713 -0.29951436  0.10412693 -0.14317351]
 [ 0.31262042 -0.11230917 -0.2205014  -0.16372357  0.13868921 -0.15533384
  -0.03882043 -0.17497262  0.06110638  0.353245 